### ISSUE TITLE
Defining PD_LONGINTTYPE in pdlibbuilder fails in some cases

### ISSUE THREAD

**Issue by DeRobyJ** [pure-data/externals-howto#12]
Currently using latest msys2/mingw-w64.
Using m_pd.h from a **Puredata 0.50.2** build.

m_pd.h can define PD_LONGINTTYPE by itself, compiling just fine, whereas the definition in pdlibbuilder fails because "unknown type name __int64". So I removed the definition flag from the pdlibbuilder and let m_pd.h define it, building fine.

**Comment by umlaeute** [comment]
hmm, it seems that there are two separate issues you are having:
- `PD_LONGINTTYPE` defaulting to an unknown type
- compiled objects not being able to load

these two issues are (most likely) unrelated. please use *separate* tickets for them.

**Comment by DeRobyJ** [comment]
I split the issues!

**Comment by Spacechild1** [comment]
> whereas the definition in pdlibbuilder fails because "unknown type name __int64"

that's strange. `__int64` is a built-in type for MSVC but MinGW should provide it as a macro for compatibility reasons. In `m_pd.h` we include `stdint.h` and by jumping through various header files in my IDE I finally get to the following line in `_mingw.h`:
`#define __int64 long long`

Maybe your setup uses the "wrong" `stdint.h`?

Anyway, pd-lib-builder should really define `PD_LONGINTTYPE` as `long long` or `int64_t` instead of `__int64`. Strictly speaking, it's not necessary to define it all since Pd 0.48-2, but it doesn't hurt to keep it in case someone uses old Pd header files...

**Comment by DeRobyJ** [comment]
Once my binaries work, I'll try re-enabling that flag and see if my mingw was the problem

**Comment by Spacechild1** [comment]
@DeRobyJ  does it work now?

**Comment by DeRobyJ** [comment]
Yup, I added the flag back, and it works.
So I just missed some tools in my msys2 installation.

Thanks!
