### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by jmrdgz17** [pure-data/externals-howto#6]
Hi, does anyone have guidance as to how to compile these examples on Windows? New to makefiles in Windows and failing miserably

**Comment by umlaeute** [comment]
type `make`.

You need MSYS/MinGW installed (and you need to run `make` from within an MSYS/MinGW shell, either for 32bit or for 64bit)

**Comment by jmrdgz17** [comment]
On MinGW 64bit, the furthest I've gotten was with make install PDDIR="C:\Program Files (x86)\Pd" PDINCLUDEDIR="C:\Program Files (x86)\Pd\src" , but still facing errors:
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Program Files (x86)\Pd/bin/pd.dll' is incompatible with i386:x86-64 output
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `helloworld.o' is incompatible with i386:x86-64 output
helloworld.o:helloworld.c:(.text+0xa): undefined reference to `__imp__post'
helloworld.o:helloworld.c:(.text+0x1b): undefined reference to `__imp__pd_new'
helloworld.o:helloworld.c:(.text+0x2f): undefined reference to `__imp__gensym'
helloworld.o:helloworld.c:(.text+0x60): undefined reference to `__imp__class_new'
helloworld.o:helloworld.c:(.text+0x76): undefined reference to `__imp__class_addbang'
collect2.exe: error: ld returned 1 exit status

**Comment by umlaeute** [comment]
> i386 architecture of input file 'helloworld.o' is incompatible with i386:x86-64 output

this error says it all.
it seems you are mixing up 64bit (the desired output) and 32bit (your Pd-installation; some intermediate files).

since you are compiling against a 32bit version of Pd, make sure to run an `MSYS/MinGW 32bit` shell.
therein do:

~~~bash
cd path/to/my/external/
make clean
make
~~~

in order to build 64bit versions, you need to install a 64bit Pd. repeat the above, but this time in a `MSYS/MinGW 64bit` shell.

The `make clean` command is important, as the build-process uses the same intermediate files regardless of architecture.

**Comment by jmrdgz17** [comment]
You're right, compiles perfectly in MinGW 64bit when pointing to a 64bit portable Pd. Thank you!

**Comment by umlaeute** [comment]
great.

btw, it should automatically find a Pd installed into `C:\Program Files\` (W64) resp `C:\Program Files (x86)\` (WOW64). (but it will not search  `C:\Program Files (x86)\ for an amd64 build, which is where you got caught)
